#!/bin/bash

function c () {
    local a
    (( $# > 0 )) && a="$@" || read -r -p "calc: " a
    bc -l <<< "$a"
}
function round()
{
  echo $(printf %.$2f $(echo "scale=$2;(((10^$2)*$1)+0.5)/(10^$2)" | bc))
};

function get_size (){
  #Find file size
  var=$(stat -c%s "$2")
  mb=$(bc <<< 'scale=2; '$var'/1000000')

  #Colors
  RED=`tput setaf 1`
  GREEN=`tput setaf 2`
  YELLOW=`tput setaf 3`
  NC=`tput sgr0`

  #Display file depending on git status
  if [[ $1 == "M" ]]
  then
    echo "${RED}Modified${NC}: $2 - $mb mb"
  fi
  if [[ $1 == "A" ]]
  then
    echo "${GREEN}Added${NC}: $2 - $mb mb"
  fi
  if [[ $1 == "U" ]]
  then
    echo "${GREEN}Updated${NC}: $2 - $mb mb"
  fi
  if [[ $1 == "D" ]]
  then
    echo "${RED}Deleted${NC}: $2 - $mb mb"
  fi
  if [[ $1 == "C" ]]
  then
    echo "${YELLOW}Copied${NC}: $2 - $mb mb"
  fi
  if [[ $1 == "R" ]]
  then
    echo "${RED}Renamed${NC}: $2 - $mb mb"
  fi
  if [[ $1 == "??" ]]
  then
    echo "${RED}Untracked${NC}: $2 - $mb mb"
  fi
}

mapfile -t git_status_files < <( git status -s )

tLen=${#git_status_files[@]}

for (( i=0; i<${tLen}; i++ ));
do
  get_size ${git_status_files[$i]}
done
